author = 'David Rodr√≠guez (@daavidrgz)'
description = ''
credits = 'https://github.com/wujiocean/dotfiles'
dependencies = [
	'paperview (https://github.com/glouw/paperview)',
	'bspwm',
	'sxhkd',
	'rofi',
	'polybar',
	'dunst',
	'pulseaudio',
	'pamixer',
	'feh',
	'brightnessctl',
	'playerctl',
	'mpd',
	'flameshot',
	'newsboat (Optional)',
	'mpd-notification (Optional)',
	'alacritty (Optional)',
	'better-discord (Optional)',
	'spicetify (Optional)',
]
