author = 'David Rodriguez (@daavidrgz)'
description = 'A simple and minimalistic desktop with rounded corners and subtle transparency.'
credits = 'https://github.com/joni22u/dotfiles'
dependencies = [
	'pulsectl (pip)',
	'bspwm',
	'sxhkd',
	'picom',
	'rofi',
	'dunst',
	'pulseaudio',
	'pamixer',
	'feh',
	'brightnessctl',
	'playerctl',
	'xob',
	'tint2',
	'flameshot',
	'alacritty (Optional)',
	'firefox (Optional)',
	'better-discord (Optional)',
	'spicetify (Optional)',
	'neofetch (Optional)',
	'bottom (Optional)',
]
